file1=open("30 days 30 hour operations.txt","w")
file1.write('I have completed 10 days successfully ')
file1.close()
file1=open("30 days 30 hour operations.txt","a")
n=input("Enter your name:")
file1.write(n)
print("Name was appended successfully")
file1.close()